# Hash con lista de países europeos

COUNTRIES = { "Österreich" => "at",
              "Belgique/België" => "be",
              "Bulgaria" => "bg",
              "Κύπρος" => "cy",
              "Česká Republika" => "cz",
              "Deutschland" => "de",
              "Danmark" => "dk",
              "Eesti" => "ee",
              "España" => "es",
              "Suomi" => "fi",
              "France" => "fr",
              "United Kingdom" => "gb",
              "Ελλάδα" => "gr",
              "Magyarország" => "hu",
              "Éire/Ireland" => "ie",
              "Italia" => "it",
              "Lietuva" => "lt",
              "Luxembourg" => "lu",
              "Latvija" => "lv",
              "Malta" => "mt",
              "Nederland" => "nl",
              "Polska" => "pl",
              "Portugal" => "pt",
              "România" => "ro",
              "Sverige" => "se",
              "Slovenija" => "si",
              "Slovensko" => "sk"
}
