# Hash con lista de países europeos

COUNTRIES = { "Austria" => "at",
              "Belgium" => "be",
              "Bulgaria" => "bg",
              "Cyprus" => "cy",
              "Czech Republic" => "cz",
              "Germany" => "de",
              "Denmark" => "dk",
              "Estonia" => "ee",
              "Spain" => "es",
              "Finland, Suomi" => "fi",
              "France" => "fr",
              "United Kingdom" => "gb",
              "Greece" => "gr",
              "Hungary" => "hu",
              "Ireland" => "ie",
              "Italy" => "it",
              "Lithuania" => "lt",
              "Luxemburg" => "lu",
              "Latvia" => "lv",
              "Malta" => "mt",
              "Netherlands" => "nl",
              "Poland" => "pl",
              "Portugal" => "pt",
              "Romania" => "ro",
              "Sweden" => "se",
              "Slovenia" => "si",
              "Slovakia" => "sk"
}
